### ISSUE TITLE
Publish wheel to pypi?

### ISSUE THREAD

**Issue by mattrobenolt** [percy/python-percy-client#10]
Inside your `Makefile` (https://github.com/percy/python-percy-client/blob/master/Makefile#L68-L70) and in `setup.cfg` (https://github.com/percy/python-percy-client/blob/master/setup.cfg#L14-L15), this has the stuff needed to build a wheel, it just appears to not have been uploaded with the release to pypi for some reason.

**Comment by fotinakis** [comment]
Yeah sorry just my misunderstanding of python package management. Just ran the `bdist_wheel` upload, let me know if that didn't work!

**Comment by mattrobenolt** [comment]
That looks right. :) Thanks!
