### ISSUE TITLE
Deprecation warning due to invalid escape sequences

### ISSUE THREAD

**Issue by tirkarthi** [percy/python-percy-client#112]
Deprecation warnings are raised due to invalid escape sequences. This can be fixed by using raw strings or escaping the literals. pyupgrade also helps in automatic conversion : https://github.com/asottile/pyupgrade/

```
find . -iname '*.py' | grep -v example | xargs -P4 -I{} python3.8 -Wall -m py_compile {}
./tests/test_user_agent.py:14: DeprecationWarning: invalid escape sequence \d
  '^Percy/v1 python-percy-client/[.\d]+ \(python/[.\d]+(; travis)?\)$',
```

**Comment by Robdel12** [comment]
Hey @tirkarthi thanks for the issue! Are you just getting started with this SDK or have you been using it for a while? This SDK has been deprecated in favor of our new python selenium SDK: https://github.com/percy/percy-python-selenium

**Comment by tirkarthi** [comment]
I am doing a project where I am filing issues regarding this deprecation on top 4000 Pypi packages and this package was one of them. I didn't know this was deprecated. Feel free to close the issue and PR if it's irrelevant.
