### ISSUE TITLE
Handle percy API failures more gracefully.

### ISSUE THREAD

**Issue by mattrobenolt** [percy/python-percy-client#12]
In our case, we exceeded our Percy quota, which resulted in our builds failing in a way that was not obvious what's going on. For example:

```
Traceback (most recent call last):
  File "/home/travis/build/getsentry/sentry/src/sentry/utils/pytest/selenium.py", line 145, in percy
    percy.initialize_build()
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/percy/runner.py", line 43, in initialize_build
    missing_resources = self._current_build['data']['relationships']['missing-resources']
KeyError: 'data'
```

The only way to debug this was to try and run percy locally (which normally isn't configured to do so since we don't have a `PERCY_TOKEN` to use). And the error in Travis CI gave us no information whatsoever.

In our case, the HTTP response just contained:

``` python
{u'errors': [{u'detail': u'This repo has exceeded the limits of the v1-large plan. The repository owner (@xxx) can visit here to upgrade: https://percy.io/account',
   u'status': u'quota_exceeded'}]}
```

**Comment by timhaines** [comment]
Fixed by https://github.com/percy/python-percy-client/pull/30

**Comment by timhaines** [comment]
Thanks for the report @mattrobenolt -- apologies for taking so long to get it fully addressed.
