### ISSUE TITLE
Set default value for `parallel_total_shards`

### ISSUE THREAD

**Issue by billyvg** [percy/python-percy-client#26]
Otherwise on CI envs you can end up with `nonce` set by default, but `total_shards` is empty.

```
{u'errors': [{u'status': u'bad_request', u'detail': u'For parallel builds, both parallel_nonce and parallel_total_shards must be given.'}]}
```

**Comment by timhaines** [comment]
Thanks @billyvg -- this is handled by just merged https://github.com/percy/python-percy-client/pull/25
