### ISSUE TITLE
Add support for github actions

### ISSUE THREAD

**Issue by s-weigand** [percy/python-percy-client#91]
Github actions is the new in github integrated CI service and it would be awesome if percy would support it.

**Comment by Robdel12** [comment]
👋 Hey @s-weigand I know you've been putting work in to this project, but it's not going to live a lot longer. We have been consolidating all our SDKs to use the same package over the past year (https://github.com/percy/percy-agent). We have a new Python selenium SDK using that package: https://github.com/percy/percy-python-selenium

Which can be integrated into GitHub actions here: https://docs.percy.io/docs/github-actions

**Comment by s-weigand** [comment]
Thanks for the quick answer and the usefull links.
PS: Having the info about the deprecation in the readme would be nice 😉

**Comment by Robdel12** [comment]
Heh, we haven't quite fully released the new Python SDK yet (it doesn't have an official docs page for example). Can't deprecate until there's something solid to move towards :)

**Comment by s-weigand** [comment]
Ok Deprecation might have been a too hard word there 😉 
But that it isn't actively developed anymore, would be a good info to have for people that want to open issues or PR's.
